### ISSUE TITLE
[Question] geofire .remove() vs firebase .remove()

### ISSUE THREAD

**Issue by apptum** [firebase/geofire-js#129]
Is there a difference if I delete a location not with `geoFire.remove("some_key")` but by using the standard firebase command `firebase.database().ref('someKey').remove();`? It seems to work fine, just wanted to make sure.

**Comment by jwngr** [comment]
The two code samples you wrote will both be equivalent if your GeoFire index is at the root of your Database (not really suggested). As you can see for [the code for `GeoFire.remove()`](https://github.com/firebase/geofire-js/blob/master/src/geoFire.js#L95), all we do is set the key to `null`, which is equivalent to calling `remove()`. However, the GeoFire index is an implementation detail and I would strongly urge you to store it in an obscure node like `_geofire` and not interact with that node directly. If you do interact with the node directly, you will most likely be broken by a future non-breaking change in the library.

Also, in the future, please read the new issue template and avoid asking usage questions like this since these kinds of things are better suited for [Stack Overflow](https://stackoverflow.com/questions/tagged/firebase) or the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk).
