### ISSUE TITLE
Angular v4

### ISSUE THREAD

**Issue by ravivit9** [firebase/geofire-js#147]
### Version info

**Firebase:**
"@angular/core": "^4.1.2"

**GeoFire:**
"geofire": "^4.1.2"

**Other (e.g. Node, browser, operating system) (if applicable):**

### Steps to reproduce

system.config.js
=============
  'geofire': {
    main: 'dist/geofire.js',
    defaultExtension: 'js',
    meta: {'dist/geofire.js': {format: 'global'}}
  },
packages: {
'geofire':                    { main: 'dist/geofire.js', defaultExtension: 'js' },
}

geofire.d.ts
=========
declare module 'geofire' {
  function GeoFire(firebaseRef: any): void;
  export = GeoFire;
}

app.component.ts
=================
import GeoFire = require('geofire');

export class AppComponent {.....
constructor(public authService: AuthService ......

      let afRefAny: any = this.db.list('locations/');
      new GeoFire (afRefAny._ref);

      var geoQuery = afRefAny.query({
        center: [51.294, -0.245],
        radius: 1
      });}
}

### Expected behavior
Geoquery to be executed and queried.

### Actual behavior
ERROR in ~/work/ajs/src/app/app.component.ts (15,1): Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

ERROR in ~/work/ajs/src/app/app.component.ts (15,26): File '~/work/ajs/src/geofire.d.ts' is not a module.

I tried in different way to solve this problem but couldn't get it resolved.

**Comment by ravivit9** [comment]
Hi All,  Anyone encountered or solved this issue before?

**Comment by nikmartin** [comment]
I use geofire in an Angular4 project with no issues:
instead of:
`import GeoFire = require('geofire');`
just install geofire as normal via npm then do 
`import GeoFire from 'geofire';`
then fake out Typescript with:
`declare var GeoFire: any;` before your class declaration
and inside your class do:
`private gf: any;`
and in your constructor, do:
`let ref = this.db.app.database().ref();`
`this.gf = new GeoFire(ref);`
and gf is now a reference to the GeoFire instance, connected to the firebase declared in this.db

**Comment by ravivit9** [comment]
@nikmartin thanks for your input. Worked well.
