### ISSUE TITLE
Typeof process Why is GeoFire only exported when running in Node 

### ISSUE THREAD

**Issue by WilfredR** [firebase/geofire-js#155]
I'd like to use GeoFire in my mobile project created with [Fusetools](http://fusetools.com)

It's not clear to me why `typeof process !== "undefined"` is included. 

```
// Export GeoFire if this is being run in node
if (typeof module !== "undefined" && typeof process !== "undefined") {
  module.exports = GeoFire;
}
```
Or in other words, what will go wrong if I export GeoFire module without process being defined.

Thanks!

**Comment by doovers** [comment]
Wondering the same thing. I'm trying to use in an Angular 6 project and `process` is `undefined`

**Comment by Hugoer** [comment]
Same problem, some solution? Thanks for the effort

**Comment by doovers** [comment]
@Hugoer Here is what I did...

> node_modules/geofire/dist/geofire.js (1223)

Move export outside of if statement because process is undefined
```typescript 
// Export GeoFire if this is being run in node
if (typeof module !== "undefined" && typeof process !== "undefined") {
}
module.exports = GeoFire; // *** Move this line out of if statement
```

**Comment by puf** [comment]
*cleaning up some old issues*

It looks like this issue was resolved by @doovers' [comment](https://github.com/firebase/geofire-js/issues/155#issuecomment-389943330). If there's anything we can do in this repo to improve matters, without breaking devs on other platforms, please reopen the issue and open a PR.
