### ISSUE TITLE
GeoQuery stuck when searching through 2 Milllion points

### ISSUE THREAD

**Issue by blackspider1994** [firebase/geofire-js#160]
### Version info

**Firebase:*3.7.0*

**GeoFire:*4.1.2*

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case
Using points in a circle .When data exceeds 1Million mark geoQuery does not return any result.

### Expected behavior
Provide points within range

### Actual behavior
Does not respond

**Comment by puf** [comment]
*Cleaning up old issues*

GeoFire is built on top of Firebase's Realtime Databases, so inherits the inherent limitations of that underlying platform. While there is no explicit maximum number of nodes in Realtime Database, a million nodes sounds a level where I suspect you're hitting the maximum RTDB can query and not a limitation of GeoFire itself.

Since there's nothing we can change in this repo to improve this, I'm closing the issue. If you find that it is actually caused by something the library does that causes the problem, feel free to reopen it with details.
