### ISSUE TITLE
geoFire.get not returning item that is in the database

### ISSUE THREAD

**Issue by Simranjitk** [firebase/geofire-js#164]
Geofire is not returning the coordinates when I search for them by the key as such:

```
geoFire.get(KEY).then(function(location){
   console.log(location);
}, function(error){ 
   console.log(error);
};
```
I have used geoFire.set(KEY) to set the location with the same key in a separate section of the application already and the retrieving happens AFTER the setting is done and it still returns NULL.

If I place geoFire.set right before geoFire.get, it works and when I remove the geoFire.set and run geoFire.get with the same key as before (which returned coordinates before), it returns NULL.

What can be the problem here? I'm having a huge issue because geoFire is not recognizing previously added locations and adding new one's to the database each time the application runs.

**Comment by puf** [comment]
Hey @Simranjitk . I'm going through some old issues, and noticed yours. I'm going to close it for now, given that it's been a few years since you reported this.

If this problem still persists, can you provide an [MCVE](http://stackoverflow.com/help/mcve) that any of us can run to reproduce the problem?
