### ISSUE TITLE
Use Firebase and GeoFire for Realtime tracking on WEB PAGE

### ISSUE THREAD

**Issue by ouchaaou** [firebase/geofire-js#174]
Hello , 
I have two user who uses a Web page.
No IOS, no Andruid.
I wanted that the user A shares his position with the user B. Both users go to see realtime on the Web page.
I wonder if Firebase, Geofire and React is the good choice?
What is what he ya links towards example ones who gathers ca?
Thank you

Click to link to see image description
https://ibb.co/gfCGyy

**Comment by MichaelSolati** [comment]
@ouchaaou so the `geofire` library is used to make queries against the RTDB to find items/docs/whatever near a location. It doesn't seem that what you want requires querying based on location, rather, you want to query based on users relationships. I don't have any links for this, but I don't think you need `geofire`.

**Comment by mcdonamp** [comment]
This is probably a better question for [Quora](https://www.quora.com/topic/Firebase) or our [Google Group](https://groups.google.com/forum/#!forum/firebase-talk), rather than the JS SDK issue tracker. The former are intended for broader architectural questions, while this is really intended for bugs or feature requests in the SDK.
