### ISSUE TITLE
Firebase version 9

### ISSUE THREAD

**Issue by jafarijason** [firebase/geofire-js#233]
Do you have a plan to support firebase v9 modular?
https://firebase.google.com/docs/web/modular-upgrade

I can contribute for using v9

**Comment by puf** [comment]
It looks like @samtstern  started on this at some point: https://github.com/firebase/geofire-js/pull/217.

This would break all backwards compatibility though, so we might need to branch into two releases.

**Comment by samtstern** [comment]
Breaking backwards compatibility is pretty normal. We do that for FirebaseUI, etc. As long as they're compatible with the latest major SDK version at the time of their release. 

Right now geofire is not forwards compatible, to use it you have to use V8 or earlier. That's not good.

**Comment by puf** [comment]
Shouldn't current GeoFire builds already be able to run on v9's compat
layer?

I get that's not ideal. Should your PR already cover all that needs to
change?

**Comment by samtstern** [comment]
@puf yes they should work well with compat for those using GeoFire via CDN. If you're building into a modern webapp via NPM ... I'm not sure.

I doubt my CL is complete, it was an experiment I did months ago. @jhuleatt can probably advise.

**Comment by jafarijason** [comment]
> It looks like @samtstern started on this at some point: #217.
> 
> This would break all backwards compatibility though, so we might need to branch into two releases.

I think if we have something like this for exporting module 
```
export { GeoCallbackRegistration, GeoCallbackRegistrationModular } from './GeoCallbackRegistration';
export { GeoFire, GeoFireModular } from './GeoFire';
export { GeoQuery, GeoQueryModular  } from './GeoQuery';
export * from './GeoFireTypes';
```
and support both compact and modular will works fine and I saw in #217 @samtstern is try ing only suppor firebase modular but with ^^^ aproach we can supoort both

**Comment by zchwyng** [comment]
+1

**Comment by PanamaDonne** [comment]
+1

**Comment by isakb** [comment]
+1

**Comment by spotvin42** [comment]
Any news on this?

**Comment by tobias74** [comment]
I have implemented a quick and dirty upgrade to version 9 "modular".

This is the branch: [https://github.com/tobias74/geofire-js/tree/upgrade-to-v9-modular](https://github.com/tobias74/geofire-js/tree/upgrade-to-v9-modular)

Sadly I currently do not have the time to make this into a proper pull request. 

I just quickly replaced the v8 statements with the v9 counterparts. Along the way I had to remove some of the types and use "any". The sourcecode just would not compile otherwise. Probably the settings in my tsconfig are wrong? 

Also I did not have the time to use proper typings for the parts that I introduced. (I know, there is no excuse for that) but I had to rush things just to get it working in my own project.

Again, appologies for this half-baked attempt. Maybe someone can help me finish it? 

(I did not even run the tests, I just used it directly in my project and everything seemed to be ok)

**Comment by evdama** [comment]
Hi folks... what's the current status on supporting fb v9?

**Comment by AliMohammad93** [comment]
is there any solution for that ?

**Comment by anckaertv** [comment]
Any news on this ? Thanks in advance

**Comment by rashearth** [comment]
Hi, first, thanks for the good app! I would also like to use the version9, looking forward!!

**Comment by thatfiredev** [comment]
Hey all!
We have just released geofire [version 6.0.0](https://github.com/firebase/geofire-js/releases/tag/6.0.0) which now supports the v9 sdk :)
Thanks patiently waiting on this! 🙏

**Comment by isakb** [comment]
Awesome! Thank you so much!

**Comment by PanamaDonne** [comment]
🎉🎉🎉 great!

Den ons 13 juli 2022 21:14Isak Bakken ***@***.***> skrev:

> Awesome! Thank you so much!
>
> On Wed, Jul 13, 2022, 21:20 Rosário Pereira Fernandes <
