### ISSUE TITLE
Firebase 2.1.1 support?

### ISSUE THREAD

**Issue by jordanthornquest** [firebase/geofire-js#60]
What will it take to approve support for the latest version of Firebase? Are there any changes in Firebase 2.1.x that would causes anything in GeoFire to break?

**Comment by jwngr** [comment]
Your wish is my command. [GeoFire 3.2.1](https://github.com/firebase/geofire-js/releases/tag/v3.2.1) now supports Firebase 2.1.x. There actually were no code changes required to the main GeoFire lib since Firebase 2.1.x was fully backwards compatible and only added new features, but I released a new version of GeoFire which updated the dependencies in the `bower.json` and `package.json`.

**Comment by jordanthornquest** [comment]
Hey, thanks a bunch! :smile:
