### ISSUE TITLE
Sample security rules could be tighter

### ISSUE THREAD

**Issue by mikepugh** [firebase/geofire-js#61]
The [sample Firebase security rules](https://github.com/firebase/geofire-js/blob/master/examples/securityRules/rules.json) allow for anyone to come in and wipe out your geofire index, with a call to fb.set(null).

I know individual requirements will vary, but it might be a good idea to point out the risk of deletion and offer an alternative, such as allowing anyone to write assuming they aren't deleting.

````javascript
{
  "rules": {
    "<your-geofire-node>": {
      // Allow anyone to read from this node
      ".read": true,
      // Index each location's geohash for faster querying
      ".indexOn": ["g"],
      // Schema validation
      "$key": {
        // Allow anyone to write to this node, assuming they respect the schema and they are not trying to delete
        ".write": "newData.exists()",
        ".validate": "newData.hasChildren(['g', 'l']) && newData.getPriority().length <= 22 && newData.getPriority().length > 0",
        "g": {
          ".validate": "newData.val() == newData.parent().getPriority()"
        },
        "l": {
          "0" : {
            ".validate": "newData.isNumber() && newData.val() >= -90 && newData.val() <= 90"
          },
          "1" : {
            ".validate": "newData.isNumber() && newData.val() >= -180 && newData.val() <= 180"
          },
          "$other": {
            ".validate": false
          }
        },
        "$other": {
          ".validate": false
        }
      }
    }
  }
}

````

**Comment by jwngr** [comment]
Yeah, I agree the default rules are a bit simplistic. But I'm not sure what's a good default to go with. The issue with putting the `".write": "newData.exists()"` rule where you did is that it will cause all `GeoFire.remove()` calls to fail, which is probably not what everyone wants. You could put the rule under the `"<your-geofire-node>"`, which would prevent you from doing a bulk delete in one command, but then would leave your child keys open to be deleted one-by-one. And it would have the weird effect of preventing all but your final child key from being removed since that would actually fail the condition as well.

I think the rules you want here are highly dependent on the use-case. If your system is set up where you have one trusted server which is doing the writing while all the clients are reading, you'd probably want a write rule which checks that the `auth.uid` is the `uid` of the server process. If you want any client to be able to write key(s) which correspond to a logged-in user, you'd probably want to key your GeoFire index by `uid` and have a rule like `".write": "auth.uid === $key"` (or `".write": "$key.startsWith(auth.uid + '-')"` if you allow a user to write multiple keys like `facebook:2421-foo` and `facebook:2421-bar` to GeoFire). If you have an app which allows anyone to add any key to GeoFire, then I think your only options are to either prevent deletes (via the rule you suggested) or allow anyone to delete anything. I don't think this is necessarily a Firebase problem though, as you'd have the same decision to make with any storage system.

Maybe the solution here is to just add a note which says "hey anyone can delete your index; if you want to prevent deletions, go with these rules, but note that it will break all calls to `remove()`." What do you think?

**Comment by mikepugh** [comment]
Exactly - my particular app does not allow anyone to delete so my rule works. But that won't hold for everyone.

The best option might be to provide a couple example rule sets, and a brief discussion of pros/cons with each strategy similar to what you wrote in your response.

**Comment by steffenfrost** [comment]
What is wrong with requiring data exists AND authentication for write to GeoFire, like everything else?

      ".write": "auth != null && !data.exists()",

We use those rules for almost everything else.  Requiring data for a write negates your ability to delete? Huh?

**Comment by mikepugh** [comment]
@steffenfrost it all depends on your use case. I have a need to allow unauthenticated writes, but I don't want them to be able to delete.
