### ISSUE TITLE
Upgrade RSVP dependency from 3.0.16 to 3.0.17

### ISSUE THREAD

**Issue by barberousse** [firebase/geofire-js#62]
Requesting a minor point release upgrade of the dependent RSVP module from 3.0.16 to 3.0.17. 3.0.16 breaks Geofire's ability to be consumed by browserify but a fix was released with 3.0.17. See the [issue](https://github.com/tildeio/rsvp.js/issues/352) and [merge](https://github.com/tildeio/rsvp.js/pull/366) in RSVP repo.

**Comment by barberousse** [comment]
The issue is line 1592 in rsvp/dist/rsvp.js:
```javascript
var vertx = require('vertx');
```
After installing geofire from npm and browserifying, this error will get thrown:
```bash
Error: module "vertx" not found from "C:\\Github\\reactsesh\\node_modules\\geofire\\node_modules\\rsvp\\dist\\rsvp.js"
```
Which is fixed by directly referring to the vertx.js shim file you have at the root instead:
```javascript
var vertx = require('../vertx.js');
```

**Comment by jwngr** [comment]
Yup, I remember this issue cropping up before (GeoFire issue #58), but RSVP still hadn't cut the 3.0.17 release. I'm glad to see that they have done so now. I just cut a 3.2.2 release of GeoFire which loosens the RSVP dependency to 3.0.x so that it should now work: https://github.com/firebase/geofire-js/releases/tag/v3.2.2. Thanks for opening this issue!
