### ISSUE TITLE
About sfVehicles Bug

### ISSUE THREAD

**Issue by juzhen21510** [firebase/geofire-js#81]
When I opened the sfVehicles index.html, then I switched to another tab in Chrome, after a while, i switched back to  sfVehicles index.html opened before, I found many vehicle icons on the map were shaking from left to right or up and down. I think it is a bug.

**Comment by jwngr** [comment]
I think this is a result of the fact that Chrome will pause JavaScript execution in inactive tabs after a certain amount of time. This will cause certain events to not fire and cause general weirdness. I wouldn't say this is a bug in GeoFire itself, but rather something that needs to be handled by the bus demo. I'm closing since I it is out of scope for the demo app.
