### ISSUE TITLE
GeoFire using too much data on client side

### ISSUE THREAD

**Issue by webdigi** [firebase/geofire-js#86]
So, we have a mobile app which filters 1000's of realtime position of cars and shows user's cars within a 5 mile radius of their current location. Geofire works as expected. Each driver app updates the position of that vehicle to Geofire. Geofire on client filters 5 mile radius of current user location.

However, geofire seems to be downloading all 1000's of cars realtime position to client and then sorting it at client side. how can we avoid this? 

Ideally we send lat, long and radius and all these queries should happen at firebase server and not at client. This is likely to load client side with a lot of incoming data.

Is there a better way to query and avoid all realtime position being streamed to client?

**Comment by jdimond** [comment]
There are two parts to this issue:
1. If the server data is [not indexed](https://www.firebase.com/docs/security/guide/indexing-data.html), the server will send down all data to the client to filter client side.
2. Since the server does not support geo queries natively, the client uses a couple of tricks to query the data using geohashes. In practice however, this means that depending on your query the client might end up querying an area that is a bit larger (~2-3 the size in the worst case) and then filtering client side. This is a limitation of how GeoFire works.

Please see if either applies to you and reopen if neither is the case.

**Comment by ajabero** [comment]
Hi Webdigi, I'm interested in knowing how you ended up dealing with this issue. Does indexing the server data help reduce the load on the client as recommended by @jdimond ? Can't you just write a cloud function for the query and do the filtering/sorting on the server instead of on the client?
